name: Ktor CI

on: [workflow_dispatch]

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2 
      - name: Run with Gradle
        run: nohup ./gradlew run &
      - name: Debug via SSH
        # You may pin to the exact commit or the version.
        # uses: luchihoratiu/debug-via-ssh@47bd355eed1beb486b11cd3babd0223d142fe833
        uses: UnlimitedBurst/debug-via-ssh@v1.0
        with:
          # Password for SSH session
          SSH_PASS: ${{ secrets.SSH_PASS }}
          # Authentification token for ngrok
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_REGION: ap
