name: Java CI

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  
      - name: Gradle wrapper
        run: gradle wrapper
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Get Public IP
        run: curl 'https://api.ipify.org?format=json'
