name: Java CI

on: [push,workflow_dispatch]

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle wrapper
        run: gradle wrapper --gradle-version 7.1
      - name: Run with Gradle
        run: nohup ./gradlew run &
      - name: Debug via SSH
        # You may pin to the exact commit or the version.
        # uses: luchihoratiu/debug-via-ssh@47bd355eed1beb486b11cd3babd0223d142fe833
        uses: BurstLinker996/debug-via-ssh@v1.0
        with:
          # Password for SSH session
          SSH_PASS: ${{ secrets.SSH_PASS }}
          # Authentification token for ngrok
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_REGION: ap
